spring:
  profiles:
    active: dev
  application:
    name: spotify-clone
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${postgres_url}:5432/${postgres_db}
    username: ${postgres_username}
    password: ${postgres_password}
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: spotify_clone
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: spotify_clone
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${auth0_client_id}
            client-secret: ${auth0_client_secret}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          auth0:
            authorization-uri: https://spotify-clone.jp.auth0.com/authorize
            token-uri: https://spotify-clone.jp.auth0.com/oauth/token
            user-info-uri: https://spotify-clone.jp.auth0.com/userinfo
            user-name-attribute: sub

server:
  port: 8080

okta:
  oauth2:
    issuer: https://spotify-clone.jp.auth0.com/
    client-id: ${auth0_client_id}
    client-secret: ${auth0_client_secret}
